# LocalSURV Windows installer (PowerShell).
#
# Usage:
#   irm https://localsurv.dev/install.ps1 | iex
#   # or, after downloading:
#   powershell -ExecutionPolicy Bypass -File install.ps1
#
# Pin a specific release tag/branch:
#   $env:LOCALSURV_VERSION = "v0.2.0"; irm ... | iex
#
# What it does:
#   1. Checks for Node >=20 and Git on PATH.
#   2. Clones / updates the repo into %USERPROFILE%\.localsurv-app
#   3. Runs `npm ci` + `npm run build`.
#   4. Generates SURVHUB_SECRET_KEY into %USERPROFILE%\.survhub\survhub.env
#   5. Registers a Scheduled Task that runs LocalSURV at user logon (no admin
#      required). To install as a true Windows Service, run this script from
#      an elevated PowerShell with -AsService.
#   6. Prints the dashboard URL.
#
# idempotent — safe to re-run. If `npm ci` or `npm run build` fails the
# installer triggers a rollback that restores the previous git ref (or
# removes the partial install directory on a fresh install) so you're
# never left with a half-built tree.

param(
  [switch] $AsService,
  [string] $InstallDir = "$env:USERPROFILE\.localsurv-app",
  [string] $DataDir = "$env:USERPROFILE\.survhub",
  [int] $Port = 8787,
  # NOTE: forking? Change <GITHUB_OWNER> here, then audit the same sentinel
  # in install.sh, apps\server\src\lib\upstream.ts, and docs\forking.md.
  [string] $RepoUrl = "https://github.com/<GITHUB_OWNER>/localsurv.git"
)

$ErrorActionPreference = "Stop"

function Write-Log($msg) { Write-Host "[localsurv] $msg" -ForegroundColor Cyan }
function Write-Warn($msg) { Write-Host "[localsurv] $msg" -ForegroundColor Yellow }
function Die($msg) { Write-Host "[localsurv] $msg" -ForegroundColor Red; exit 1 }

# rollback: restore the previous git ref or, on a fresh install, remove the
# half-built directory. Tracked via $script: scoped variables so the
# trap-equivalent below sees them.
$script:RollbackRef = ""
$script:RollbackFreshInstall = $false
function Invoke-Rollback {
  if ($script:RollbackFreshInstall) {
    if (Test-Path $InstallDir) {
      Write-Warn "Removing partial install at $InstallDir"
      Remove-Item -Recurse -Force -Path $InstallDir
    }
  } elseif ($script:RollbackRef -and (Test-Path (Join-Path $InstallDir ".git"))) {
    Write-Warn "Resetting $InstallDir to previous ref $($script:RollbackRef)"
    git -C $InstallDir reset --hard $script:RollbackRef | Out-Null
  }
}

# -- 1. prerequisites --------------------------------------------------------

foreach ($cmd in @("git", "node", "npm")) {
  if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
    Die "Missing dependency: $cmd. Install Node 20+ from https://nodejs.org and Git from https://git-scm.com."
  }
}

$nodeMajor = [int]((node -p "process.versions.node.split('.')[0]") -as [string])
if ($nodeMajor -lt 20) { Die "Node.js 20+ is required (found $(node --version))." }

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  Write-Warn "Docker is not installed. Process services still work; Docker services and managed databases will not."
}

# -- 2. clone / update -------------------------------------------------------

$version = $env:LOCALSURV_VERSION
$installParent = Split-Path $InstallDir -Parent
if (-not (Test-Path $installParent)) { New-Item -ItemType Directory -Path $installParent | Out-Null }

if (Test-Path (Join-Path $InstallDir ".git")) {
  Write-Log "Updating $InstallDir"
  $script:RollbackRef = (git -C $InstallDir rev-parse HEAD).Trim()
  git -C $InstallDir fetch --prune --tags
  if ($version) {
    Write-Log "Checking out pinned version: $version"
    git -C $InstallDir reset --hard $version
  } else {
    git -C $InstallDir reset --hard origin/HEAD
  }
} else {
  Write-Log "Cloning $RepoUrl into $InstallDir"
  $script:RollbackFreshInstall = $true
  if ($version) {
    git clone --depth 1 --branch $version $RepoUrl $InstallDir
    if ($LASTEXITCODE -ne 0) {
      Write-Warn "Branch/tag not found; falling back to default + checkout"
      git clone $RepoUrl $InstallDir
      git -C $InstallDir checkout $version
    }
  } else {
    git clone --depth 1 $RepoUrl $InstallDir
  }
}

Set-Location $InstallDir

# -- 3. install + build ------------------------------------------------------

Write-Log "Installing dependencies"
npm ci
if ($LASTEXITCODE -ne 0) { Invoke-Rollback; Die "npm ci failed (rollback applied)" }
Write-Log "Building"
npm run build
if ($LASTEXITCODE -ne 0) { Invoke-Rollback; Die "npm run build failed (rollback applied)" }

# -- 4. secrets + data dir ---------------------------------------------------

if (-not (Test-Path $DataDir)) { New-Item -ItemType Directory -Path $DataDir | Out-Null }
$envFile = Join-Path $DataDir "survhub.env"
if (-not (Test-Path $envFile)) {
  $secret = node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("base64"))'
  @(
    "# Generated by install.ps1 - keep this file secret.",
    "SURVHUB_SECRET_KEY=`"$secret`"",
    "SURVHUB_DATA_DIR=`"$DataDir`"",
    "SURVHUB_PORT=$Port"
  ) | Set-Content -Path $envFile -Encoding UTF8
  # ACL: owner read/write only.
  $acl = Get-Acl $envFile
  $acl.SetAccessRuleProtection($true, $false)
  $rule = New-Object System.Security.AccessControl.FileSystemAccessRule($env:USERNAME, "FullControl", "Allow")
  $acl.AddAccessRule($rule)
  Set-Acl -Path $envFile -AclObject $acl
  Write-Log "Generated $envFile"
}

# -- 5. service / scheduled task --------------------------------------------

$nodeBin = (Get-Command node).Source
$serverEntry = Join-Path $InstallDir "apps\server\dist\index.js"
$wrapper = Join-Path $DataDir "localsurv-launch.ps1"

@(
  "# Generated by install.ps1 - launches LocalSURV with env file loaded.",
  "Get-Content '$envFile' | ForEach-Object {",
  "  if (`$_ -match '^([^=]+)=(.*)$') {",
  "    `$key = `$Matches[1].Trim()",
  "    `$val = `$Matches[2].Trim('`"')",
  "    if (`$key -and -not `$key.StartsWith('#')) { Set-Item env:`$key `$val }",
  "  }",
  "}",
  "& '$nodeBin' '$serverEntry'"
) | Set-Content -Path $wrapper -Encoding UTF8

if ($AsService) {
  Write-Log "Registering as a Windows Service requires elevation and node-windows. Run from an elevated PowerShell:"
  Write-Log "  npm install -g node-windows"
  Write-Log "  node $InstallDir\packaging\windows-service.js install"
  Write-Warn "Service install path is documented but not auto-executed; falling back to scheduled task."
}

$taskName = "LocalSURV"
$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -File `"$wrapper`""
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)

if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
  Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
}
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Description "LocalSURV control plane" -User $env:USERNAME | Out-Null
Start-ScheduledTask -TaskName $taskName

# -- 6. done ----------------------------------------------------------------

Write-Log "LocalSURV is installed."
Write-Log "Dashboard: http://localhost:$Port"
Write-Log "First-run steps:"
Write-Log "  1. Open the URL above in your browser"
Write-Log "  2. Bootstrap the admin user from the dashboard"
Write-Log "  3. Deploy your first service from the Services page"
Write-Log "Manage the scheduled task with: Get-ScheduledTask -TaskName LocalSURV"
