#!/usr/bin/env bash
#
# LocalSURV one-line installer.
# Usage:
#   curl -fsSL https://localsurv.dev/install.sh | bash
#
# What it does:
#   1. Detects OS and required tooling (node >= 20, git, docker optional)
#   2. Clones / updates the repo into $HOME/.local/share/localsurv
#   3. Runs npm ci && npm run build
#   4. Generates a SURVHUB_SECRET_KEY if one isn't already set
#   5. Writes a systemd user service (Linux) or launchd plist (macOS) that
#      starts LocalSURV on boot
#   6. Prints the URL to open in the browser
#
# This script is idempotent — you can re-run it to update to the latest commit.

set -euo pipefail

REPO_URL="${LOCALSURV_REPO:-https://github.com/your-org/localsurv.git}"
INSTALL_DIR="${LOCALSURV_DIR:-$HOME/.local/share/localsurv}"
DATA_DIR="${SURVHUB_DATA_DIR:-$HOME/.survhub}"
PORT="${SURVHUB_PORT:-8787}"

log()  { printf '\033[1;34m[localsurv]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[localsurv]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[localsurv]\033[0m %s\n' "$*" >&2; exit 1; }

# -- 1. prerequisites --------------------------------------------------------

need() { command -v "$1" >/dev/null 2>&1 || die "Missing dependency: $1"; }
need git
need node
need npm

NODE_MAJOR=$(node -p "process.versions.node.split('.')[0]")
if [ "$NODE_MAJOR" -lt 20 ]; then
  die "Node.js 20+ is required (found $(node --version))"
fi

if ! command -v docker >/dev/null 2>&1; then
  warn "Docker is not installed. Process-type services still work, but Docker services and managed databases will not."
fi

# -- 2. clone / update -------------------------------------------------------

mkdir -p "$(dirname "$INSTALL_DIR")"
if [ -d "$INSTALL_DIR/.git" ]; then
  log "Updating $INSTALL_DIR"
  git -C "$INSTALL_DIR" fetch --prune
  git -C "$INSTALL_DIR" reset --hard origin/HEAD
else
  log "Cloning $REPO_URL into $INSTALL_DIR"
  git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# -- 3. install + build ------------------------------------------------------

log "Installing dependencies"
npm ci
log "Building"
npm run build

# -- 4. secrets + data dir ---------------------------------------------------

mkdir -p "$DATA_DIR"
ENV_FILE="$DATA_DIR/survhub.env"
if [ ! -f "$ENV_FILE" ]; then
  SECRET=$(node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("base64"))')
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh — keep this file secret.
SURVHUB_SECRET_KEY="$SECRET"
SURVHUB_DATA_DIR="$DATA_DIR"
SURVHUB_PORT=$PORT
EOF
  chmod 600 "$ENV_FILE"
  log "Generated $ENV_FILE"
fi

# -- 5. service manager ------------------------------------------------------

OS="$(uname -s)"
NODE_BIN="$(command -v node)"
SERVER_ENTRY="$INSTALL_DIR/apps/server/dist/index.js"

case "$OS" in
  Linux)
    UNIT_DIR="$HOME/.config/systemd/user"
    mkdir -p "$UNIT_DIR"
    cat > "$UNIT_DIR/localsurv.service" <<EOF
[Unit]
Description=LocalSURV control plane
After=network.target

[Service]
Type=simple
EnvironmentFile=$ENV_FILE
ExecStart=$NODE_BIN $SERVER_ENTRY
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
    log "Wrote $UNIT_DIR/localsurv.service"
    if command -v systemctl >/dev/null 2>&1; then
      systemctl --user daemon-reload
      systemctl --user enable --now localsurv.service || warn "Could not start service automatically"
    fi
    ;;
  Darwin)
    PLIST="$HOME/Library/LaunchAgents/dev.localsurv.plist"
    mkdir -p "$(dirname "$PLIST")"
    cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>dev.localsurv</string>
  <key>ProgramArguments</key>
  <array>
    <string>$NODE_BIN</string>
    <string>$SERVER_ENTRY</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>SURVHUB_DATA_DIR</key><string>$DATA_DIR</string>
    <key>SURVHUB_PORT</key><string>$PORT</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$DATA_DIR/stdout.log</string>
  <key>StandardErrorPath</key><string>$DATA_DIR/stderr.log</string>
</dict>
</plist>
EOF
    log "Wrote $PLIST"
    launchctl unload "$PLIST" >/dev/null 2>&1 || true
    launchctl load "$PLIST" || warn "launchctl load failed"
    ;;
  *)
    warn "Unknown OS $OS — start LocalSURV manually with: node $SERVER_ENTRY"
    ;;
esac

# -- 6. done ----------------------------------------------------------------

log "LocalSURV is installed."
log "Dashboard: http://localhost:$PORT"
log "First-run steps:"
log "  1. Open the URL above in your browser"
log "  2. Go to Settings → Bootstrap admin user"
log "  3. Deploy your first service from the Services page"
