#!/usr/bin/env node
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const args = process.argv.slice(2);
const command = args[0] ?? "start";

const here = path.dirname(fileURLToPath(import.meta.url));
const entry = path.join(here, "index.js");

function printHelp(): void {
  process.stdout.write(
    `LocalSURV — self-hosted deploy platform

Usage: survhub <command>

Commands:
  start           Start the LocalSURV server (API + dashboard)
  init            Create ~/.survhub, generate SURVHUB_SECRET_KEY, write an env file
  version         Print version information
  help            Show this help

Environment:
  SURVHUB_SECRET_KEY   Required. AES-256-GCM key for at-rest encryption.
  SURVHUB_PORT         API port (default 8787)
  SURVHUB_DATA_DIR     State directory (default ~/.survhub)

See docs/configuration.md for the full list.
`
  );
}

function printVersion(): void {
  try {
    const pkgPath = path.resolve(here, "../package.json");
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
    process.stdout.write(`survhub ${pkg.version ?? "?"}\n`);
  } catch {
    process.stdout.write("survhub (unknown version)\n");
  }
}

function cmdInit(): void {
  const dataDir = process.env.SURVHUB_DATA_DIR ?? path.join(os.homedir(), ".survhub");
  fs.mkdirSync(dataDir, { recursive: true });
  const envFile = path.join(dataDir, "survhub.env");
  if (fs.existsSync(envFile)) {
    process.stdout.write(`Environment file already exists at ${envFile}\n`);
    return;
  }
  const secret = crypto.randomBytes(32).toString("base64");
  const body = [
    "# Generated by `survhub init` — keep this file secret.",
    "# Source it before starting: `set -a && source ~/.survhub/survhub.env && set +a`",
    "",
    `SURVHUB_SECRET_KEY="${secret}"`,
    `SURVHUB_DATA_DIR="${dataDir}"`,
    "SURVHUB_PORT=8787",
    ""
  ].join("\n");
  fs.writeFileSync(envFile, body, { mode: 0o600 });
  process.stdout.write(
    `Wrote ${envFile}\n` +
    `Data directory: ${dataDir}\n\n` +
    `Next:\n` +
    `  set -a && source ${envFile} && set +a\n` +
    `  survhub start\n`
  );
}

function cmdStart(): void {
  if (!process.env.SURVHUB_SECRET_KEY) {
    process.stderr.write(
      "WARNING: SURVHUB_SECRET_KEY is not set. Secrets will not be persisted encrypted.\n" +
      "Run `survhub init` to generate one, or export it manually before starting.\n"
    );
  }
  const child = spawn(process.execPath, [entry], { stdio: "inherit", env: process.env });
  child.on("exit", (code) => process.exit(code ?? 0));
}

switch (command) {
  case "start":
  case "server":
    cmdStart();
    break;
  case "init":
    cmdInit();
    break;
  case "version":
  case "--version":
  case "-v":
    printVersion();
    break;
  case "help":
  case "--help":
  case "-h":
    printHelp();
    break;
  default:
    process.stderr.write(`Unknown command: ${command}\n\n`);
    printHelp();
    process.exit(2);
}
