# Companion to localsurv.wxs — runs once after MSI install to drop a
# Scheduled Task that starts LocalSURV at user logon. Mirrors the path
# install.ps1 takes when invoked outside the MSI flow. Idempotent.

$ErrorActionPreference = "Stop"

$installDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$dataDir = "$env:USERPROFILE\.survhub"
$envFile = Join-Path $dataDir "survhub.env"
$nodeBin = (Get-Command node -ErrorAction SilentlyContinue)?.Source

if (-not $nodeBin) {
    Write-Host "Node 20+ is required. Install from https://nodejs.org and re-run this script." -ForegroundColor Yellow
    exit 1
}

if (-not (Test-Path $dataDir)) { New-Item -ItemType Directory -Path $dataDir | Out-Null }

if (-not (Test-Path $envFile)) {
    $secret = node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("base64"))'
    @(
        "# Generated by LocalSURV MSI installer.",
        "SURVHUB_SECRET_KEY=`"$secret`"",
        "SURVHUB_DATA_DIR=`"$dataDir`"",
        "SURVHUB_PORT=8787"
    ) | Set-Content -Path $envFile -Encoding UTF8
    Write-Host "Generated $envFile" -ForegroundColor Cyan
}

$serverEntry = Join-Path $installDir "apps\server\dist\index.js"
$wrapper = Join-Path $dataDir "localsurv-launch.ps1"

@(
    "Get-Content '$envFile' | ForEach-Object {",
    "  if (`$_ -match '^([^=]+)=(.*)$') {",
    "    `$key = `$Matches[1].Trim()",
    "    `$val = `$Matches[2].Trim('`"')",
    "    if (`$key -and -not `$key.StartsWith('#')) { Set-Item env:`$key `$val }",
    "  }",
    "}",
    "& '$nodeBin' '$serverEntry'"
) | Set-Content -Path $wrapper -Encoding UTF8

$taskName = "LocalSURV"
$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -File `"$wrapper`""
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)

if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
}
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Description "LocalSURV control plane" -User $env:USERNAME | Out-Null
Start-ScheduledTask -TaskName $taskName

Write-Host ""
Write-Host "LocalSURV is now registered to start at user logon." -ForegroundColor Green
Write-Host "Dashboard: http://localhost:8787"
