#!/usr/bin/env bash
#
# Build a macOS .pkg installer for LocalSURV.
#
# Inputs:
#   $VERSION                — semver string, e.g. 0.2.0
#   $PKG_OUT                — output path, defaults to ./dist/localsurv-<version>.pkg
#   $APPLE_DEVELOPER_ID     — optional. "Developer ID Installer: Name (TEAMID)" — triggers signing.
#   $APPLE_NOTARY_PROFILE   — optional. notarytool keychain profile name — triggers notarization + stapling.
#
# What ships:
#   /usr/local/localsurv/        ← repo source tree (no node_modules, no .git)
#   /usr/local/bin/localsurv     ← thin launcher script that exec's `node`
#
# Postinstall:
#   - runs `npm ci --omit=dev` once
#   - creates ~/.survhub with a generated SURVHUB_SECRET_KEY
#   - registers ~/Library/LaunchAgents/dev.localsurv.plist (per-user)
#
# This script is intentionally idempotent and can be run in CI on
# macos-latest or locally for smoke-testing.

set -euo pipefail

VERSION="${VERSION:-0.0.0}"
PKG_OUT="${PKG_OUT:-dist/localsurv-${VERSION}.pkg}"
PKG_ID="dev.localsurv.installer"
INSTALL_PREFIX="/usr/local/localsurv"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

ROOT="$WORK/root"
SCRIPTS="$WORK/scripts"
mkdir -p "$ROOT$INSTALL_PREFIX" "$ROOT/usr/local/bin" "$SCRIPTS"

# 1. Stage the source tree -------------------------------------------------

# Copy source minus heavy/irrelevant directories. We deliberately ship the
# pre-built dist so the user can run immediately; node_modules is installed
# by the postinstall script.
rsync -a \
  --exclude=node_modules \
  --exclude=.git \
  --exclude=.github \
  --exclude=apps/web/dist \
  --exclude="*.pkg" \
  --include="apps/server/dist/" \
  --include="apps/web/dist/" \
  "$REPO_ROOT/" "$ROOT$INSTALL_PREFIX/"

# Re-include the built artifacts that rsync just excluded (we WANT them)
mkdir -p "$ROOT$INSTALL_PREFIX/apps/server/dist" "$ROOT$INSTALL_PREFIX/apps/web/dist"
[ -d "$REPO_ROOT/apps/server/dist" ] && cp -R "$REPO_ROOT/apps/server/dist/." "$ROOT$INSTALL_PREFIX/apps/server/dist/"
[ -d "$REPO_ROOT/apps/web/dist" ] && cp -R "$REPO_ROOT/apps/web/dist/." "$ROOT$INSTALL_PREFIX/apps/web/dist/"

# 2. Launcher script ------------------------------------------------------

cat > "$ROOT/usr/local/bin/localsurv" <<'EOF'
#!/usr/bin/env bash
INSTALL_PREFIX="/usr/local/localsurv"
ENV_FILE="${SURVHUB_DATA_DIR:-$HOME/.survhub}/survhub.env"
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi
exec node "$INSTALL_PREFIX/apps/server/dist/cli.js" "$@"
EOF
chmod +x "$ROOT/usr/local/bin/localsurv"

# 3. Postinstall script ---------------------------------------------------

cat > "$SCRIPTS/postinstall" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

INSTALL_PREFIX="/usr/local/localsurv"
DATA_DIR="${SURVHUB_DATA_DIR:-$HOME/.survhub}"
ENV_FILE="$DATA_DIR/survhub.env"

# Production deps only — we shipped pre-built dist, so we skip dev tooling.
cd "$INSTALL_PREFIX"
if command -v npm >/dev/null 2>&1; then
  npm ci --omit=dev || npm install --omit=dev
fi

# First-run secret + env file
mkdir -p "$DATA_DIR"
if [ ! -f "$ENV_FILE" ]; then
  SECRET="$(node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("base64"))')"
  cat > "$ENV_FILE" <<ENVEOF
# Generated by LocalSURV installer — keep this file secret.
SURVHUB_SECRET_KEY="$SECRET"
SURVHUB_DATA_DIR="$DATA_DIR"
SURVHUB_PORT=8787
ENVEOF
  chmod 600 "$ENV_FILE"
fi

# Per-user launchd agent
PLIST="$HOME/Library/LaunchAgents/dev.localsurv.plist"
mkdir -p "$(dirname "$PLIST")"
cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>dev.localsurv</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/localsurv</string>
    <string>start</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$DATA_DIR/stdout.log</string>
  <key>StandardErrorPath</key><string>$DATA_DIR/stderr.log</string>
</dict>
</plist>
PLISTEOF

launchctl unload "$PLIST" >/dev/null 2>&1 || true
launchctl load "$PLIST" || true

exit 0
EOF
chmod +x "$SCRIPTS/postinstall"

# 4. pkgbuild -------------------------------------------------------------

mkdir -p "$(dirname "$PKG_OUT")"
UNSIGNED_PKG="$WORK/localsurv-unsigned.pkg"
pkgbuild \
  --root "$ROOT" \
  --identifier "$PKG_ID" \
  --version "$VERSION" \
  --scripts "$SCRIPTS" \
  --install-location "/" \
  "$UNSIGNED_PKG"

# 5. Sign + notarize (optional) ------------------------------------------

if [ -n "${APPLE_DEVELOPER_ID:-}" ]; then
  echo "[build-pkg] signing with $APPLE_DEVELOPER_ID"
  productsign --sign "$APPLE_DEVELOPER_ID" "$UNSIGNED_PKG" "$PKG_OUT"
  if [ -n "${APPLE_NOTARY_PROFILE:-}" ]; then
    echo "[build-pkg] notarizing via profile $APPLE_NOTARY_PROFILE"
    xcrun notarytool submit "$PKG_OUT" --keychain-profile "$APPLE_NOTARY_PROFILE" --wait
    xcrun stapler staple "$PKG_OUT"
  fi
else
  echo "[build-pkg] APPLE_DEVELOPER_ID not set — emitting unsigned .pkg"
  cp "$UNSIGNED_PKG" "$PKG_OUT"
fi

echo "[build-pkg] wrote $PKG_OUT"
