/**
 * LocalSURV desktop wrapper. Boots the existing server as a child process,
 * picks a free port, waits for /health, then opens a BrowserWindow at that
 * port. Quit kills the server. No webview embedding tricks — the server
 * keeps doing what it always did, the wrapper just hosts a window.
 *
 * Iterating? After editing apps/server/src or apps/web/src, run
 * `npm run build` from the repo root, then quit & relaunch this app.
 */

"use strict";

const { app, BrowserWindow, dialog, shell, Menu } = require("electron");
const { spawn, spawnSync } = require("node:child_process");
const path = require("node:path");
const fs = require("node:fs");
const os = require("node:os");
const crypto = require("node:crypto");
const net = require("node:net");

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const SERVER_ENTRY = path.join(REPO_ROOT, "apps", "server", "dist", "index.js");
const DATA_DIR = process.env.SURVHUB_DATA_DIR || path.join(os.homedir(), ".survhub");
const ENV_FILE = path.join(DATA_DIR, "survhub.env");

let serverProcess = null;
let mainWindow = null;

function isPortFree(port) {
  return new Promise((resolve) => {
    const s = net.createServer();
    s.once("error", () => resolve(false));
    s.once("listening", () => s.close(() => resolve(true)));
    s.listen(port, "127.0.0.1");
  });
}

async function findFreePort(start = 8787) {
  for (let p = start; p < start + 50; p++) {
    if (await isPortFree(p)) return p;
  }
  throw new Error(`No free port between ${start} and ${start + 50}`);
}

function loadOrCreateEnvFile() {
  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
  if (!fs.existsSync(ENV_FILE)) {
    const secret = crypto.randomBytes(32).toString("base64");
    fs.writeFileSync(
      ENV_FILE,
      [
        "# Generated by LocalSURV desktop app — keep this file secret.",
        `SURVHUB_SECRET_KEY="${secret}"`,
        `SURVHUB_DATA_DIR="${DATA_DIR}"`,
        ""
      ].join("\n"),
      { mode: 0o600 }
    );
  }
  const env = {};
  for (const raw of fs.readFileSync(ENV_FILE, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const m = /^([A-Za-z0-9_]+)=(.*)$/.exec(line);
    if (!m) continue;
    env[m[1]] = m[2].replace(/^"(.*)"$/, "$1");
  }
  return env;
}

async function waitForServer(port, timeoutMs = 30_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      await fetch(`http://127.0.0.1:${port}/health`, {
        signal: AbortSignal.timeout(1000)
      });
      return; // any response means the port is bound
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 200));
  }
  throw new Error("Server did not respond within 30s");
}

function findSystemNode() {
  // Don't reuse Electron's `process.execPath`. Electron embeds Node 20's ABI;
  // native modules (better-sqlite3) compiled against the system Node load
  // there with a NODE_MODULE_VERSION mismatch. Run the server under the
  // user's regular `node` instead.
  if (process.env.LOCALSURV_NODE && fs.existsSync(process.env.LOCALSURV_NODE)) {
    return process.env.LOCALSURV_NODE;
  }
  const probe = process.platform === "win32" ? "where.exe" : "which";
  const out = spawnSync(probe, ["node"], { encoding: "utf8" });
  if (out.status === 0 && out.stdout) {
    const first = out.stdout
      .split(/\r?\n/)
      .map((s) => s.trim())
      .filter(Boolean)[0];
    if (first && fs.existsSync(first)) return first;
  }
  // Common Homebrew + nvm fallbacks on macOS / Linux.
  const fallbacks = [
    "/opt/homebrew/bin/node",
    "/usr/local/bin/node",
    "/usr/bin/node",
    path.join(os.homedir(), ".nvm/versions/node")
  ];
  for (const f of fallbacks) {
    if (fs.existsSync(f) && fs.statSync(f).isFile()) return f;
  }
  return null;
}

async function startServer() {
  if (!fs.existsSync(SERVER_ENTRY)) {
    dialog.showErrorBox(
      "Build needed",
      `Server bundle not found at:\n${SERVER_ENTRY}\n\n` +
        `Run from the repo root:\n  npm run build\n\nthen relaunch the app.`
    );
    app.quit();
    return null;
  }
  const nodeBin = findSystemNode();
  if (!nodeBin) {
    dialog.showErrorBox(
      "Node not found",
      "Could not find a system `node` binary on PATH.\n\n" +
        "LocalSURV's server uses better-sqlite3, which has a native binding " +
        "compiled against your system Node — Electron's embedded Node has a " +
        "different ABI and can't load it.\n\n" +
        "Fix: install Node 20+ from https://nodejs.org or via Homebrew, then " +
        "relaunch.\n\nOr set $LOCALSURV_NODE to an explicit node path."
    );
    app.quit();
    return null;
  }
  const fileEnv = loadOrCreateEnvFile();
  const port = await findFreePort();
  serverProcess = spawn(nodeBin, [SERVER_ENTRY], {
    env: { ...process.env, ...fileEnv, SURVHUB_PORT: String(port) },
    stdio: ["ignore", "pipe", "pipe"]
  });
  serverProcess.stdout.on("data", (d) => process.stdout.write(`[server] ${d}`));
  serverProcess.stderr.on("data", (d) => process.stderr.write(`[server] ${d}`));
  serverProcess.on("exit", (code, signal) => {
    serverProcess = null;
    if (mainWindow && !mainWindow.isDestroyed()) {
      dialog.showErrorBox("Server exited", `LocalSURV server stopped (code=${code} signal=${signal}).`);
      app.quit();
    }
  });
  await waitForServer(port);
  return port;
}

function createMainWindow(port) {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 900,
    minHeight: 600,
    title: "LocalSURV",
    backgroundColor: "#020617",
    webPreferences: {
      contextIsolation: true,
      sandbox: true
    }
  });
  mainWindow.loadURL(`http://127.0.0.1:${port}`);

  // Keep external links opening in the user's browser, not inside the app.
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith(`http://127.0.0.1:${port}`)) return { action: "allow" };
    void shell.openExternal(url);
    return { action: "deny" };
  });
}

function buildMenu() {
  const isMac = process.platform === "darwin";
  const template = [
    ...(isMac
      ? [
          {
            label: app.name,
            submenu: [
              { role: "about" },
              { type: "separator" },
              { role: "hide" },
              { role: "hideOthers" },
              { role: "unhide" },
              { type: "separator" },
              { role: "quit" }
            ]
          }
        ]
      : []),
    {
      label: "View",
      submenu: [
        { role: "reload" },
        { role: "forceReload" },
        { role: "toggleDevTools" },
        { type: "separator" },
        { role: "resetZoom" },
        { role: "zoomIn" },
        { role: "zoomOut" },
        { type: "separator" },
        { role: "togglefullscreen" }
      ]
    },
    {
      label: "LocalSURV",
      submenu: [
        {
          label: "Open Data Directory…",
          click: () => void shell.openPath(DATA_DIR)
        },
        {
          label: "Open Env File…",
          click: () => void shell.openPath(ENV_FILE)
        }
      ]
    }
  ];
  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
}

app.whenReady().then(async () => {
  buildMenu();
  try {
    const port = await startServer();
    if (port == null) return;
    createMainWindow(port);
  } catch (err) {
    dialog.showErrorBox("Failed to launch", err && err.stack ? err.stack : String(err));
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0 && serverProcess) {
    // Shouldn't generally happen on macOS since we quit on window-close, but
    // protects against the standard "click Dock icon to reopen" idiom.
  }
});

app.on("window-all-closed", () => {
  app.quit();
});

app.on("before-quit", () => {
  if (serverProcess) {
    try {
      serverProcess.kill("SIGTERM");
    } catch {
      /* ignore */
    }
  }
});
