import { nanoid } from "nanoid";
import type { AppContext } from "../../../types.js";
import {
  broadcast,
  dbReservedPorts,
  dockerUnavailableMessage,
  findFreePort,
  nowIso,
  serializeError
} from "../../../lib/core.js";
import {
  buildConnectionString,
  containerNameForDatabase,
  createManagedDatabase,
  getContainerStatus,
  getDatabase,
  removeDatabase,
  type DatabaseRow
} from "../../databases.js";
import { scanForDatabaseDrivers } from "../../codeScan.js";
import {
  createResource,
  deleteResource,
  getResource,
  linkResourceToService,
  listLinksForResource,
  resourceConfig,
  unlinkResource,
  updateResourceRuntimeState,
  updateResourceStatus,
  type ManagedResourceRow
} from "../lifecycle.js";
import { setResourceSecret } from "../secrets.js";
import {
  envFromResourceConfig,
  type DetectionSignal,
  type ProvisionInput,
  type ProvisionPlan,
  type ResourceProfile,
  type ResourceStatus
} from "../profiles.js";
import { restartOrRedeployService } from "../restart.js";

/**
 * Factory for "legacy-database-backed" resource profiles (Redis, MySQL, MongoDB).
 *
 * The postgres profile (profiles/postgres.ts) is the template: provisioning
 * goes through the SAME primitive as POST /databases (`createManagedDatabase`),
 * so a resource-provisioned database is a first-class legacy database too —
 * it writes the `databases` row, points `services.linked_database_id` at it,
 * and records a `managed_resources` row carrying `config_json.database_id`.
 * All existing /databases/* management (backups, logs, transfer, browser)
 * keeps working on it unchanged, and env() injects the profile's generated URL
 * synchronously from the legacy row.
 */

export type ManagedDbProfileOptions = {
  id: "redis" | "mysql" | "mongo";
  label: string;
  engine: DatabaseRow["engine"];
  /**
   * Driver labels from scanForDatabaseDrivers that indicate this engine,
   * mapped to the confidence a hit carries (direct drivers are near-certain;
   * multi-DB ORMs would be medium — codeScan currently only emits direct
   * labels for these engines).
   */
  drivers: Record<string, "high" | "medium">;
  /**
   * Host port window for findFreePort. Must not collide with the postgres
   * window (54320–54420, shared with the embedded-SQLite promote flow and the
   * default Supabase stack ports 54321–54324).
   */
  portRange: [number, number];
  /** Env var generated by this profile. SQL-ish engines use DATABASE_URL; Redis uses REDIS_URL. */
  envKey?: "DATABASE_URL" | "REDIS_URL";
};

function highestConfidence(signals: DetectionSignal[]): "high" | "medium" | "low" {
  if (signals.some((signal) => signal.confidence === "high")) return "high";
  if (signals.some((signal) => signal.confidence === "medium")) return "medium";
  return "low";
}

type ServiceRow = {
  id: string;
  project_id: string | null;
  name: string;
  working_dir: string | null;
};

function getServiceRow(ctx: AppContext, serviceId: string): ServiceRow {
  const service = ctx.db
    .prepare("SELECT id, project_id, name, working_dir FROM services WHERE id = ?")
    .get(serviceId) as ServiceRow | undefined;
  if (!service) throw new Error("Service not found");
  return service;
}

/** The legacy databases row backing this resource (config_json.database_id). */
function legacyDatabaseFor(ctx: AppContext, resource: ManagedResourceRow) {
  const config = resourceConfig(resource);
  const databaseId = typeof config.database_id === "string" ? config.database_id : null;
  return databaseId ? getDatabase(ctx, databaseId) : null;
}

function linkedResourceForServiceProfile(
  ctx: AppContext,
  serviceId: string,
  profile: ManagedDbProfileOptions["id"]
): ManagedResourceRow | null {
  const resource = ctx.db
    .prepare(
      `SELECT mr.*
       FROM managed_resources mr
       JOIN service_resource_links l ON l.resource_id = mr.id
       WHERE l.service_id = ? AND l.active = 1 AND mr.profile = ?
       ORDER BY mr.created_at DESC
       LIMIT 1`
    )
    .get(serviceId, profile) as ManagedResourceRow | undefined;
  return resource && legacyDatabaseFor(ctx, resource) ? resource : null;
}

function rememberedDatabaseFor(
  ctx: AppContext,
  opts: { projectId: string; engine: DatabaseRow["engine"]; name: string }
): DatabaseRow | null {
  return (
    (ctx.db
      .prepare(
        "SELECT * FROM databases WHERE project_id = ? AND engine = ? AND name = ? ORDER BY created_at DESC LIMIT 1"
      )
      .get(opts.projectId, opts.engine, opts.name) as DatabaseRow | undefined) ?? null
  );
}

export function buildManagedDbProfile(options: ManagedDbProfileOptions): ResourceProfile {
  const { id, label, engine, drivers, portRange, envKey = "DATABASE_URL" } = options;

  function detectSignals(servicePath: string): DetectionSignal[] {
    return scanForDatabaseDrivers(servicePath)
      .filter((signal) => signal.driver in drivers)
      .map((signal) => ({
        kind: "package" as const,
        value: signal.driver,
        source_file: signal.source_file,
        confidence: drivers[signal.driver]
      }));
  }

  async function provision(ctx: AppContext, input: ProvisionInput): Promise<ManagedResourceRow> {
    const service = getServiceRow(ctx, input.serviceId);
    const projectId = input.projectId ?? service.project_id ?? "";
    const resourceName = input.name ?? `${service.name}-db`;
    const existing = linkedResourceForServiceProfile(ctx, service.id, id);
    if (existing) return existing;

    const resource = createResource(ctx, {
      projectId: input.projectId ?? service.project_id,
      name: resourceName,
      profile: id,
      status: "provisioning",
      config: { ...(input.config ?? {}) }
    });
    broadcast(ctx, {
      type: "resource_status",
      resourceId: resource.id,
      status: "provisioning",
      profile: id
    });

    async function finish(db: DatabaseRow): Promise<ManagedResourceRow> {
      const latest = getResource(ctx, resource.id);
      if (!latest) throw new Error("Resource row disappeared during provisioning");
      // Legacy compatibility: the service keeps a linked database row; runtime
      // injects DATABASE_URL for SQL-ish engines and REDIS_URL for Redis.
      ctx.db
        .prepare("UPDATE services SET linked_database_id = ?, updated_at = ? WHERE id = ?")
        .run(db.id, nowIso(), service.id);

      updateResourceRuntimeState(ctx, resource.id, {
        config: { ...resourceConfig(latest), database_id: db.id },
        ports: { [engine]: db.port },
        containers: [containerNameForDatabase(db)]
      });
      // Encrypted copy of the connection string (the legacy row keeps its own
      // plaintext columns — unchanged existing behavior).
      setResourceSecret(ctx, resource.id, envKey, buildConnectionString(db), true);

      linkResourceToService(ctx, { serviceId: service.id, resourceId: resource.id });

      if (input.restart !== false) {
        try {
          await restartOrRedeployService(ctx, service.id);
        } catch (error) {
          broadcast(ctx, {
            type: "resource_provisioning",
            resourceId: resource.id,
            step: "restart",
            message: `Service restart failed (database is up): ${serializeError(error)}`
          });
        }
      }

      updateResourceStatus(ctx, resource.id, "ready");
      broadcast(ctx, {
        type: "resource_status",
        resourceId: resource.id,
        status: "ready",
        profile: id
      });
      return getResource(ctx, resource.id)!;
    }

    try {
      const remembered = rememberedDatabaseFor(ctx, { projectId, engine, name: resourceName });
      if (remembered) return await finish(remembered);

      try {
        await ctx.docker.ping();
      } catch (error) {
        throw new Error(
          dockerUnavailableMessage(error) ?? `Docker is not reachable: ${serializeError(error)}`
        );
      }

      const port = await findFreePort(portRange[0], portRange[1], dbReservedPorts(ctx));
      const databaseName = service.name.replace(/[^a-zA-Z0-9_]/g, "_") || "appdb";
      // username/databaseName defaults come from createManagedDatabase (the
      // shared primitive also used by POST /databases) — stay consistent.
      const db = await createManagedDatabase(ctx, {
        projectId,
        name: resourceName,
        engine,
        port,
        password: nanoid(16),
        databaseName
      });

      return await finish(db);
    } catch (error) {
      const failed = getResource(ctx, resource.id);
      if (failed) {
        updateResourceRuntimeState(ctx, resource.id, {
          config: { ...resourceConfig(failed), error: serializeError(error) }
        });
      }
      updateResourceStatus(ctx, resource.id, "failed");
      broadcast(ctx, {
        type: "resource_status",
        resourceId: resource.id,
        status: "failed",
        profile: id
      });
      throw error instanceof Error ? error : new Error(String(error));
    }
  }

  return {
    id,
    label,
    detect(servicePath: string): DetectionSignal[] {
      return detectSignals(servicePath);
    },
    async plan(ctx: AppContext, serviceId): Promise<ProvisionPlan> {
      const service = ctx.db
        .prepare("SELECT id, project_id, working_dir FROM services WHERE id = ?")
        .get(serviceId) as { id: string; project_id: string | null; working_dir: string | null } | undefined;
      if (!service) throw new Error("Service not found");
      const signals = detectSignals(service.working_dir ?? "");
      return {
        profile: id,
        service_id: serviceId,
        project_id: service.project_id,
        confidence: signals.length > 0 ? highestConfidence(signals) : "low",
        signals,
        actions: [
          {
            id: `create-${id}`,
            label: `Create managed ${label} and inject ${envKey}`,
            risk: "safe",
            default_enabled: true
          }
        ],
        env: { generated: [envKey], required_user_input: [], optional_user_input: [], injected: [] }
      };
    },
    async provision(ctx, input): Promise<ManagedResourceRow> {
      return provision(ctx, input);
    },
    async status(ctx, resourceId): Promise<ResourceStatus> {
      const resource = getResource(ctx, resourceId);
      if (!resource) return "error";
      const db = legacyDatabaseFor(ctx, resource);
      if (!db) return (resource.status as ResourceStatus) ?? "error";
      try {
        const { state } = await getContainerStatus(ctx, db);
        if (state === "running") return "running";
        if (state === "not-found") return "error";
        return "stopped";
      } catch {
        return (resource.status as ResourceStatus) ?? "error";
      }
    },
    /** SYNC: connection URL resolved from the legacy databases row (local DB only). */
    env(ctx, resourceId, serviceId): Record<string, string> {
      const resource = getResource(ctx, resourceId);
      if (!resource) return {};
      const env = envFromResourceConfig(resource);
      const db = legacyDatabaseFor(ctx, resource);
      if (db) {
        const service = ctx.db.prepare("SELECT type FROM services WHERE id = ?").get(serviceId) as
          | { type?: string }
          | undefined;
        const host = service?.type === "docker" ? "host.docker.internal" : "localhost";
        env[envKey] = buildConnectionString(db, host);
      }
      return env;
    },
    async remove(ctx, resourceId): Promise<void> {
      const resource = getResource(ctx, resourceId);
      if (!resource) return;
      const db = legacyDatabaseFor(ctx, resource);
      if (db) {
        // Shared removal path: drops the container+volume row and warns services
        // whose linked_database_id pointed at it (same semantics as /databases).
        await removeDatabase(ctx, db);
      }
      for (const link of listLinksForResource(ctx, resourceId)) {
        unlinkResource(ctx, link.service_id, resourceId);
      }
      deleteResource(ctx, resourceId);
    }
  };
}
